# COLORS
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
COLOR_VEL = 5
DEFINED_COLOR = [255, 255, 255]
COLOR_DIRECTION = [-1, -1, -1]

# BALL
BALL_MAX_VEL = 5
BALL_COLOR = WHITE
BALL_RADIUS = 7

# PADDLE
PADDLE_VEL = 4
PADDLE_COLOR = WHITE
PADDLE_WIDTH = 20
PADDLE_HEIGHT = 100

# WINDOW
WINDOW_WIDTH = 700
WINDOW_HEIGHT = 500

# FONTS SIZE
WELCOME_FONT_SIZE = 20
SCORE_FONT_SIZE = 50

# FPS
FPS = 60

# WINNING_SCORE
WINNING_SCORE = 5

# PLAYERS INFO
LEFT_PLAYER_COLOR = 'blue'
RIGHT_PLAYER_COLOR = 'red'